feat(TAS-30): added project routes
WAVONA-team/connect_team pull request #11
Opened 2023-12-08 18:30 UTC by aguilam

2023-12-10 21:15 UTC, VofSwords requested changes
Информация о мутациях в trpc:
https://trpc.io/docs/quickstart#4-adding-a-mutation-procedure
https://github.com/trpc/trpc/discussions/1638#discussioncomment-2341051

Добавь в `server/api/root.ts`:

```typescript
import { userRouter } from "./routers/user";
export const appRouter = createTRPCRouter({
  user: userRouter,
});
```

2023-12-10 21:15 UTC, VofSwords commented on src/server/api/routers/project.ts
> +  .query(async ({ ctx, input }) => {
мутация

2023-12-10 21:15 UTC, VofSwords commented on src/server/api/routers/project.ts
> +    .query(async ({ ctx, input }) => {
мутация

2023-12-10 21:15 UTC, VofSwords commented on src/server/api/routers/project.ts
> +    .query(async ({ ctx, input }) => {
мутация

2023-12-12 12:56 UTC, aguilam commented
Поменял на mutation, заменил названия, а так же изменил root, но теперь происходит конфликт в root.ts потому что за это время ветка ушла немного назад по коммитам

2023-12-12 12:57 UTC, merged