TAS-129: switch
WAVONA-team/connect_team pull request #33
Opened 2023-12-22 10:14 UTC by Vo7kov

2023-12-23 19:45 UTC, VofSwords requested changes

2023-12-23 19:48 UTC, VofSwords commented on src/ui/switch/Switch.tsx
> +type Props = {
Блин, когда в последний раз смотрел было состояние загрузки, сейчас хз
спрошу у Даши

2023-12-24 13:45 UTC, Vo7kov commented on src/ui/switch/Switch.tsx
> +        onClick={onChange}
У onChange свой тип, из за того, что это headless ui. А вот у onClick стандартный тип (React.MouseEventHandler<HTMLButtonElement>)

2023-12-26 17:02 UTC, VofSwords commented on src/ui/switch/Switch.tsx
> +        onClick={onChange}
Так в том и смысл, мы должны использовать то что предоставляет headless.
Так например oChange у headless отслеживает если мы с клавиатуры сфокусировались и отменили. По хорошему нам и в наших комопонентах надо будет сделать кастомные хендлеры, но т.к. пока в этом потребности нет мы используем стандартные html

2023-12-26 17:03 UTC, VofSwords commented on src/ui/switch/Switch.tsx
> +type Props = {
Пока загрузку не делаем все ок

2024-01-11 14:30 UTC, VofSwords approved these changes

2024-01-11 17:28 UTC, merged